// Generated by CIRCT firtool-1.155.0
`ifndef layers_FullPrecisionDotProduct24_Verification
  `define layers_FullPrecisionDotProduct24_Verification
`endif // not def layers_FullPrecisionDotProduct24_Verification
