// Generated by CIRCT firtool-1.155.0
`ifndef layers_FullPrecisionDotProduct24_Verification_Cover
  `define layers_FullPrecisionDotProduct24_Verification_Cover
  `include "layers-FullPrecisionDotProduct24-Verification.sv"
`endif // not def layers_FullPrecisionDotProduct24_Verification_Cover
