// Generated by CIRCT firtool-1.155.0
`ifndef layers_NarrowCohortDotProduct24_Verification
  `define layers_NarrowCohortDotProduct24_Verification
`endif // not def layers_NarrowCohortDotProduct24_Verification
