// Generated by CIRCT firtool-1.155.0
`ifndef layers_IndependentRoundDotProduct24_Verification
  `define layers_IndependentRoundDotProduct24_Verification
`endif // not def layers_IndependentRoundDotProduct24_Verification
