// Generated by CIRCT firtool-1.155.0
`ifndef layers_IndependentRoundDotProduct24_Verification_Cover
  `define layers_IndependentRoundDotProduct24_Verification_Cover
  `include "layers-IndependentRoundDotProduct24-Verification.sv"
`endif // not def layers_IndependentRoundDotProduct24_Verification_Cover
