// Generated by CIRCT firtool-1.155.0
`ifndef layers_NarrowCohortDotProduct24_Verification_Cover
  `define layers_NarrowCohortDotProduct24_Verification_Cover
  `include "layers-NarrowCohortDotProduct24-Verification.sv"
`endif // not def layers_NarrowCohortDotProduct24_Verification_Cover
