// Generated by CIRCT firtool-1.155.0
module CohortRound4Combinational(
  input  [2:0] io_prefix_0,
               io_prefix_1,
               io_prefix_2,
               io_prefix_3,
  output [2:0] io_upCount
);

  wire [5:0] _GEN =
    {3'h0, io_prefix_3}
    + {1'h0, {2'h0, io_prefix_2} + {1'h0, {1'h0, io_prefix_1} + {1'h0, io_prefix_0}}}
    + 6'h2;
  assign io_upCount = _GEN[5:3] + {2'h0, _GEN[2:0] > 3'h4 | _GEN[2:0] == 3'h4 & _GEN[3]};
endmodule

