// Generated by CIRCT firtool-1.155.0
module NarrowCohortDotProduct24(
  input         clock,
                reset,
  input  [15:0] io_a_0,
                io_a_1,
                io_a_2,
                io_a_3,
                io_a_4,
                io_a_5,
                io_a_6,
                io_a_7,
                io_a_8,
                io_a_9,
                io_a_10,
                io_a_11,
                io_a_12,
                io_a_13,
                io_a_14,
                io_a_15,
                io_a_16,
                io_a_17,
                io_a_18,
                io_a_19,
                io_a_20,
                io_a_21,
                io_a_22,
                io_a_23,
                io_b_0,
                io_b_1,
                io_b_2,
                io_b_3,
                io_b_4,
                io_b_5,
                io_b_6,
                io_b_7,
                io_b_8,
                io_b_9,
                io_b_10,
                io_b_11,
                io_b_12,
                io_b_13,
                io_b_14,
                io_b_15,
                io_b_16,
                io_b_17,
                io_b_18,
                io_b_19,
                io_b_20,
                io_b_21,
                io_b_22,
                io_b_23,
  input         io_start,
  output        io_ready,
                io_done,
  output [19:0] io_result
);

  wire [2:0]        _selector_io_upCount;
  wire              _mult_io_done;
  wire [45:0]       _mult_io_result;
  reg               state;
  reg  [4:0]        idx;
  reg  [1:0]        groupPos;
  reg               fired;
  reg  [18:0]       groupFloor;
  reg  [22:0]       acc;
  reg  [2:0]        prefixRegs_0;
  reg  [2:0]        prefixRegs_1;
  reg  [2:0]        prefixRegs_2;
  reg  [2:0]        prefixRegs_3;
  reg               doneReg;
  reg  [19:0]       resultReg;
  wire [31:0][15:0] _GEN =
    {{io_a_0},
     {io_a_0},
     {io_a_0},
     {io_a_0},
     {io_a_0},
     {io_a_0},
     {io_a_0},
     {io_a_0},
     {io_a_23},
     {io_a_22},
     {io_a_21},
     {io_a_20},
     {io_a_19},
     {io_a_18},
     {io_a_17},
     {io_a_16},
     {io_a_15},
     {io_a_14},
     {io_a_13},
     {io_a_12},
     {io_a_11},
     {io_a_10},
     {io_a_9},
     {io_a_8},
     {io_a_7},
     {io_a_6},
     {io_a_5},
     {io_a_4},
     {io_a_3},
     {io_a_2},
     {io_a_1},
     {io_a_0}};
  wire [31:0][15:0] _GEN_0 =
    {{io_b_0},
     {io_b_0},
     {io_b_0},
     {io_b_0},
     {io_b_0},
     {io_b_0},
     {io_b_0},
     {io_b_0},
     {io_b_23},
     {io_b_22},
     {io_b_21},
     {io_b_20},
     {io_b_19},
     {io_b_18},
     {io_b_17},
     {io_b_16},
     {io_b_15},
     {io_b_14},
     {io_b_13},
     {io_b_12},
     {io_b_11},
     {io_b_10},
     {io_b_9},
     {io_b_8},
     {io_b_7},
     {io_b_6},
     {io_b_5},
     {io_b_4},
     {io_b_3},
     {io_b_2},
     {io_b_1},
     {io_b_0}};
  wire              _GEN_1 = groupPos == 2'h0;
  wire              _GEN_2 = groupPos == 2'h1;
  wire              _GEN_3 = groupPos == 2'h2;
  wire              _GEN_4 = &groupPos;
  always @(posedge clock) begin
    if (reset) begin
      state <= 1'h0;
      idx <= 5'h0;
      groupPos <= 2'h0;
      fired <= 1'h0;
      groupFloor <= 19'h0;
      acc <= 23'h0;
      prefixRegs_0 <= 3'h0;
      prefixRegs_1 <= 3'h0;
      prefixRegs_2 <= 3'h0;
      prefixRegs_3 <= 3'h0;
      doneReg <= 1'h0;
      resultReg <= 20'h0;
    end
    else begin
      automatic logic [18:0] _nextGroupFloor_T;
      automatic logic        closesGroup;
      automatic logic        isLast;
      automatic logic [19:0] _GEN_5;
      automatic logic [22:0] _nextAcc_T_1;
      automatic logic        _GEN_6;
      automatic logic        _GEN_7;
      automatic logic        _GEN_8;
      _nextGroupFloor_T = {{2{_mult_io_result[31]}}, _mult_io_result[31:15]} + groupFloor;
      closesGroup = &groupPos;
      isLast = idx == 5'h17;
      _GEN_5 = {17'h0, _selector_io_upCount} + {_nextGroupFloor_T[18], _nextGroupFloor_T};
      _nextAcc_T_1 = {{3{_GEN_5[19]}}, _GEN_5} + acc;
      _GEN_6 = closesGroup & isLast;
      _GEN_7 = state & _mult_io_done & _GEN_6;
      _GEN_8 = state & _mult_io_done & closesGroup;
      if (state) begin
        automatic logic _GEN_9 = state & _mult_io_done;
        state <= ~_GEN_7;
        if (_GEN_9) begin
          if (closesGroup) begin
            if (~isLast) begin
              idx <= idx + 5'h1;
              groupPos <= 2'h0;
              groupFloor <= 19'h0;
            end
          end
          else begin
            idx <= idx + 5'h1;
            groupPos <= groupPos + 2'h1;
            groupFloor <= _nextGroupFloor_T;
          end
        end
        if (~_GEN_8 | isLast) begin
        end
        else
          acc <= _nextAcc_T_1;
        if (~_GEN_9 | closesGroup | ~_GEN_1) begin
        end
        else
          prefixRegs_0 <= _mult_io_result[14:12];
        if (~_GEN_9 | closesGroup | ~_GEN_2) begin
        end
        else
          prefixRegs_1 <= _mult_io_result[14:12];
        if (~_GEN_9 | closesGroup | ~_GEN_3) begin
        end
        else
          prefixRegs_2 <= _mult_io_result[14:12];
        if (~_GEN_9 | closesGroup | ~_GEN_4) begin
        end
        else
          prefixRegs_3 <= _mult_io_result[14:12];
      end
      else begin
        state <= io_start;
        if (io_start) begin
          idx <= 5'h0;
          groupPos <= 2'h0;
          groupFloor <= 19'h0;
          acc <= 23'h0;
          prefixRegs_0 <= 3'h0;
          prefixRegs_1 <= 3'h0;
          prefixRegs_2 <= 3'h0;
          prefixRegs_3 <= 3'h0;
        end
      end
      fired <= state ? ~_mult_io_done | _GEN_6 : ~io_start & fired;
      doneReg <= state & _GEN_8 & isLast;
      if (state & _GEN_7)
        resultReg <= _nextAcc_T_1[19:0];
    end
  end // always @(posedge)
  SignedDigitSerialMultiplier mult (
    .clock     (clock),
    .reset     (reset),
    .io_a      (_GEN[idx]),
    .io_b      (_GEN_0[idx]),
    .io_start  (state & ~fired),
    .io_done   (_mult_io_done),
    .io_result (_mult_io_result)
  );
  CohortRound4Combinational selector (
    .io_prefix_0 (_mult_io_done & _GEN_1 ? _mult_io_result[14:12] : prefixRegs_0),
    .io_prefix_1 (_mult_io_done & _GEN_2 ? _mult_io_result[14:12] : prefixRegs_1),
    .io_prefix_2 (_mult_io_done & _GEN_3 ? _mult_io_result[14:12] : prefixRegs_2),
    .io_prefix_3 (_mult_io_done & _GEN_4 ? _mult_io_result[14:12] : prefixRegs_3),
    .io_upCount  (_selector_io_upCount)
  );
  assign io_ready = ~state;
  assign io_done = doneReg;
  assign io_result = resultReg;
endmodule

