// Generated by CIRCT firtool-1.155.0
module DigitSerialMAC(
  input         clock,
                reset,
  input  [16:0] io_a,
  input         io_start,
  input  [3:0]  io_digitIn,
  input         io_digitValid,
                io_clearAcc,
  output        io_macValid,
  output [44:0] io_acc
);

  reg        state;
  reg [16:0] regA;
  reg [2:0]  digitCnt;
  reg [17:0] pReg;
  reg [3:0]  lowChunks_0;
  reg [3:0]  lowChunks_1;
  reg [3:0]  lowChunks_2;
  reg [3:0]  lowChunks_3;
  reg [44:0] accReg;
  reg        macValidReg;
  always @(posedge clock) begin
    automatic logic [21:0] sum;
    sum = {4'h0, pReg} + {1'h0, {4'h0, regA} * {17'h0, io_digitIn}};
    if (reset) begin
      state <= 1'h0;
      digitCnt <= 3'h0;
      pReg <= 18'h0;
      accReg <= 45'h0;
      macValidReg <= 1'h0;
    end
    else begin
      automatic logic _GEN;
      automatic logic isLast;
      automatic logic _GEN_0;
      _GEN = state & io_digitValid;
      isLast = digitCnt == 3'h4;
      _GEN_0 = state & io_digitValid & isLast;
      if (state) begin
        state <= ~_GEN_0;
        if (~_GEN | isLast) begin
        end
        else
          digitCnt <= digitCnt + 3'h1;
        if (_GEN)
          pReg <= sum[21:4];
      end
      else begin
        state <= io_start;
        if (io_start) begin
          digitCnt <= 3'h0;
          pReg <= 18'h0;
        end
      end
      if (io_clearAcc)
        accReg <= 45'h0;
      else if (state & _GEN_0)
        accReg <=
          accReg + {8'h0, sum[20:0], lowChunks_3, lowChunks_2, lowChunks_1, lowChunks_0};
      macValidReg <= state & _GEN & isLast;
    end
    if (~state & io_start)
      regA <= io_a;
    if (state & io_digitValid & digitCnt == 3'h0)
      lowChunks_0 <= sum[3:0];
    if (state & io_digitValid & digitCnt == 3'h1)
      lowChunks_1 <= sum[3:0];
    if (state & io_digitValid & digitCnt == 3'h2)
      lowChunks_2 <= sum[3:0];
    if (state & io_digitValid & digitCnt == 3'h3)
      lowChunks_3 <= sum[3:0];
  end // always @(posedge)
  assign io_macValid = macValidReg;
  assign io_acc = accReg;
endmodule

