// Generated by CIRCT firtool-1.155.0
module IndependentRoundDotProduct24(
  input         clock,
                reset,
  input  [15:0] io_a_0,
                io_a_1,
                io_a_2,
                io_a_3,
                io_a_4,
                io_a_5,
                io_a_6,
                io_a_7,
                io_a_8,
                io_a_9,
                io_a_10,
                io_a_11,
                io_a_12,
                io_a_13,
                io_a_14,
                io_a_15,
                io_a_16,
                io_a_17,
                io_a_18,
                io_a_19,
                io_a_20,
                io_a_21,
                io_a_22,
                io_a_23,
                io_b_0,
                io_b_1,
                io_b_2,
                io_b_3,
                io_b_4,
                io_b_5,
                io_b_6,
                io_b_7,
                io_b_8,
                io_b_9,
                io_b_10,
                io_b_11,
                io_b_12,
                io_b_13,
                io_b_14,
                io_b_15,
                io_b_16,
                io_b_17,
                io_b_18,
                io_b_19,
                io_b_20,
                io_b_21,
                io_b_22,
                io_b_23,
  input         io_start,
  output        io_ready,
                io_done,
  output [19:0] io_result
);

  wire              _mult_io_done;
  wire [45:0]       _mult_io_result;
  reg               state;
  reg  [4:0]        idx;
  reg               fired;
  reg  [22:0]       acc;
  reg               doneReg;
  reg  [19:0]       resultReg;
  wire [31:0][15:0] _GEN =
    {{io_a_0},
     {io_a_0},
     {io_a_0},
     {io_a_0},
     {io_a_0},
     {io_a_0},
     {io_a_0},
     {io_a_0},
     {io_a_23},
     {io_a_22},
     {io_a_21},
     {io_a_20},
     {io_a_19},
     {io_a_18},
     {io_a_17},
     {io_a_16},
     {io_a_15},
     {io_a_14},
     {io_a_13},
     {io_a_12},
     {io_a_11},
     {io_a_10},
     {io_a_9},
     {io_a_8},
     {io_a_7},
     {io_a_6},
     {io_a_5},
     {io_a_4},
     {io_a_3},
     {io_a_2},
     {io_a_1},
     {io_a_0}};
  wire [31:0][15:0] _GEN_0 =
    {{io_b_0},
     {io_b_0},
     {io_b_0},
     {io_b_0},
     {io_b_0},
     {io_b_0},
     {io_b_0},
     {io_b_0},
     {io_b_23},
     {io_b_22},
     {io_b_21},
     {io_b_20},
     {io_b_19},
     {io_b_18},
     {io_b_17},
     {io_b_16},
     {io_b_15},
     {io_b_14},
     {io_b_13},
     {io_b_12},
     {io_b_11},
     {io_b_10},
     {io_b_9},
     {io_b_8},
     {io_b_7},
     {io_b_6},
     {io_b_5},
     {io_b_4},
     {io_b_3},
     {io_b_2},
     {io_b_1},
     {io_b_0}};
  always @(posedge clock) begin
    if (reset) begin
      state <= 1'h0;
      idx <= 5'h0;
      fired <= 1'h0;
      acc <= 23'h0;
      doneReg <= 1'h0;
      resultReg <= 20'h0;
    end
    else begin
      automatic logic [17:0] contribution =
        {_mult_io_result[31], _mult_io_result[31:15]}
        + {17'h0,
           _mult_io_result[14:0] > 15'h4000 | _mult_io_result[14:0] == 15'h4000
             & _mult_io_result[15]};
      automatic logic [22:0] _nextAcc_T_1;
      automatic logic        isLast;
      automatic logic        _GEN_1;
      automatic logic        _GEN_2;
      _nextAcc_T_1 = {{5{contribution[17]}}, contribution} + acc;
      isLast = idx == 5'h17;
      _GEN_1 = state & _mult_io_done & isLast;
      _GEN_2 = state & _mult_io_done;
      if (state) begin
        state <= ~_GEN_1;
        if (~_GEN_2 | isLast) begin
        end
        else begin
          idx <= idx + 5'h1;
          acc <= _nextAcc_T_1;
        end
      end
      else begin
        state <= io_start;
        if (io_start) begin
          idx <= 5'h0;
          acc <= 23'h0;
        end
      end
      fired <= state ? ~_mult_io_done | isLast : ~io_start & fired;
      doneReg <= state & _GEN_2 & isLast;
      if (state & _GEN_1)
        resultReg <= _nextAcc_T_1[19:0];
    end
  end // always @(posedge)
  SignedDigitSerialMultiplier mult (
    .clock     (clock),
    .reset     (reset),
    .io_a      (_GEN[idx]),
    .io_b      (_GEN_0[idx]),
    .io_start  (state & ~fired),
    .io_done   (_mult_io_done),
    .io_result (_mult_io_result)
  );
  assign io_ready = ~state;
  assign io_done = doneReg;
  assign io_result = resultReg;
endmodule

