// Generated by CIRCT firtool-1.155.0
module SignedDigitSerialMultiplier(
  input         clock,
                reset,
  input  [15:0] io_a,
                io_b,
  input         io_start,
  output        io_done,
  output [45:0] io_result
);

  wire        _inner_io_macValid;
  wire [44:0] _inner_io_acc;
  reg         state;
  reg  [16:0] magBShift;
  reg         signReg;
  reg  [45:0] resultReg;
  reg         doneReg;
  wire [16:0] _GEN = {io_a[15], io_a};
  wire        inner_io_clearAcc = state & _inner_io_macValid;
  always @(posedge clock) begin
    if (reset) begin
      state <= 1'h0;
      resultReg <= 46'h0;
      doneReg <= 1'h0;
    end
    else begin
      automatic logic _GEN_0;
      _GEN_0 = state & _inner_io_macValid;
      if (state)
        state <= ~_GEN_0;
      else
        state <= io_start;
      if (state & _GEN_0) begin
        automatic logic [45:0] _GEN_1 = {1'h0, _inner_io_acc};
        resultReg <= signReg ? 46'h0 - _GEN_1 : _GEN_1;
      end
      doneReg <= inner_io_clearAcc;
    end
    if (state)
      magBShift <= {4'h0, magBShift[16:4]};
    else if (io_start) begin
      automatic logic [16:0] _GEN_2 = {io_b[15], io_b};
      magBShift <= io_b[15] ? 17'h0 - _GEN_2 : _GEN_2;
    end
    if (~state & io_start)
      signReg <= io_a[15] ^ io_b[15];
  end // always @(posedge)
  DigitSerialMAC inner (
    .clock         (clock),
    .reset         (reset),
    .io_a          (io_a[15] ? 17'h0 - _GEN : _GEN),
    .io_start      (~state & io_start),
    .io_digitIn    (magBShift[3:0]),
    .io_digitValid (state),
    .io_clearAcc   (inner_io_clearAcc),
    .io_macValid   (_inner_io_macValid),
    .io_acc        (_inner_io_acc)
  );
  assign io_done = doneReg;
  assign io_result = resultReg;
endmodule

